service: doing-api
variablesResolutionMode: 20210326

custom:
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: ${env:SERVERLESS_LAYERS_BUCKET, 'lcs-layers'}
  env: ${lower(${opt:stage, self:provider.stage})}
  vpcSettings:
    prod:
      securityGroupIds: ${split(${env:SECURITY_GROUP_IDS, 'sg-052314a1eec2f2567'}, ',')}
      subnetIds: ${split(${env:SUBNET_IDS, 'subnet-01a6b61d749d10c46'}, ',')}
    current: ${ternary( ${self:custom.env}, prod, ${self:custom.vpcSettings.prod}, ~ )}

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 10
  region: ${env:AWS_REGION, 'us-east-2'}
  iam:
    role: arn:aws:iam::${aws:accountId}:role/ChurchAppsRole
  environment:
    APP_ENV: ${self:custom.env}

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /
    vpc: ${self:custom.vpcSettings.current}
  nightly:
    handler: lambda.nightly
    vpc: ${self:custom.vpcSettings.current}

plugins:
  - serverless-layers
  - serverless-plugin-utils
